kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
  DatastoreURL: "ds:///vmfs/volumes/vsan:529aba229313b8dc-1115c743db4b2b62"
